[build-system]
requires = ["setuptools>=77.0.3", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ensemble_eeg-custom"
version = "0.2.1-custom"
dependencies = [
    "fire",
    "numpy",
    "defusedxml",
    "dateparser",
]
requires-python = ">=3.10"
authors = [
  { name="Bauke van der Velde" }
  { name = "Jérémy Sadoine" },
]
maintainers = [
  { name="Aymeric Gaudin" },
  { name="Dimitri Papadopoulos Orfanos" },
]
description = "Package customisé pour anonymiser et pré-traiter les fichiers EDF pour l'étude ENSEMBLE (version modifiée par Jérémy Sadoine)"
readme = "README.md"
license-files = [ "LICENSE", "NOTICE" ]
classifiers = [
    "Programming Language :: Python",
    "Operating System :: OS Independent",
]

[project.scripts]
anonymize_eeg_ensemble = "ensemble_eeg:_anonymize_eeg_ensemble_main"

[project.urls]
Repository = "https://github.com/jsadoine/ensemble_eeg-custom.git"

[tool.setuptools]
packages = ["ensemble_eeg"]

[tool.ruff.lint]
extend-select = [
    "UP",
    "I",
    "B",
    "C4",
    "PIE",
    "PYI",
    "SIM",
    "PGH",
    "FLY",
    "PERF",
    "FURB",
    "RUF",
]
ignore = [
    "UP038",  # https://github.com/astral-sh/ruff/issues/7871
	"B028",
	"PYI024",
	"SIM115",
	"RUF005",
]
